name = "PackagePage"
uuid = "e7214860-93a8-4f22-b43d-bd447d1a2094"
authors = ["Thibaut Lienart <ltib@me.com>"]
version = "0.1.0"

[deps]
Franklin = "713c75ef-9fc9-4b05-94a9-213340da978e"

[compat]
Franklin = "0.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
